import { redirect } from 'next/navigation';
import { eq } from 'drizzle-orm';
import { db } from '@/lib/db/drizzle';
import { memberships, organizations } from '@/lib/db/schema';
import { getSession } from '@/lib/auth/session';
import { OnboardingFlow } from './_components/onboarding-flow';

export const metadata = { title: 'Bienvenue — Contravo' };

/**
 * First-run setup.
 *
 * Reached from the gate in `middleware.ts` whenever an organization has no
 * `onboarding_completed_at`. Guarded here too rather than trusting the gate
 * alone: navigating straight to `/onboarding` afterwards must not offer to
 * rewrite an organization that is already configured.
 */
export default async function OnboardingPage() {
  const user = await getSession();
  if (!user) redirect('/sign-in');

  const [row] = await db
    .select({ organization: organizations })
    .from(memberships)
    .innerJoin(organizations, eq(memberships.organizationId, organizations.id))
    .where(eq(memberships.userId, user.id))
    .limit(1);

  if (!row) redirect('/sign-in');
  if (row.organization.onboardingCompletedAt) redirect('/dashboard');

  // Sign-up sets `fullName` to the local part of the address for want of
  // anything better. Pre-filling the field with it means the reader has to clear
  // someone else's guess before typing their own name — so it is treated as
  // absent, exactly like the placeholder organization name.
  const looksAutoGenerated = user.fullName === user.email.split('@')[0];

  return (
    <OnboardingFlow
      defaultFullName={looksAutoGenerated ? '' : (user.fullName ?? '')}
      defaultOrganizationName={row.organization.name}
      contactEmail={user.email}
    />
  );
}
