import { db } from '@/lib/db/drizzle';
import { clients, files, memberships, organizations, projects, users } from '@/lib/db/schema';
import { and, eq, inArray } from 'drizzle-orm';
import { generatePublicToken } from '@/lib/public-tokens';
import { getPresignedGetUrl } from '@/lib/storage/presign';
import {
  generateContractPdf,
  generateInvoicePdf,
  generateQuotePdf,
} from '@/lib/pdf/generate.service';
import { getAppUrl } from '@/lib/config/app-url';
import { formatMoney } from '@/lib/money';

/**
 * Builds the `data` payload carried by outbound webhook events (MVP3 §6).
 *
 * n8n consumes these events to send transactional emails (MVP5 §3.2) and reads a
 * fixed set of fields — client, org, number, portalUrl, pdfUrl, teamEmails — so
 * they are assembled here once instead of being re-derived at each call site.
 *
 * Everything is best-effort: a webhook payload must never be the reason a state
 * transition fails, so enrichment errors degrade to a smaller payload.
 */

export type EntityKind = 'quote' | 'contract' | 'invoice' | 'deliverable' | 'review_request';

/** Portal actions granted by the token minted for the recipient. */
const PORTAL_ACTIONS: Record<EntityKind, string[]> = {
  quote: ['read', 'sign'],
  contract: ['read', 'sign'],
  invoice: ['read', 'pay'],
  deliverable: ['read', 'approve', 'reject'],
  review_request: ['read', 'submit_review'],
};

/** Portal path segment per entity, matching app/api/v1/portal/*. */
const PORTAL_PATH: Record<EntityKind, string> = {
  quote: 'quotes',
  contract: 'contracts',
  invoice: 'invoices',
  deliverable: 'deliverables',
  review_request: 'reviews',
};

function baseUrl(): string {
  return getAppUrl();
}

/**
 * Returns the emails of members who should be notified internally.
 *
 * Restricted to owners and admins: MVP5 §3.2 routes team notifications to
 * decision makers, not to every member of the organization.
 */
async function loadTeamEmails(organizationId: string): Promise<string[]> {
  const rows = await db
    .select({ email: users.email, role: memberships.role })
    .from(memberships)
    .innerJoin(users, eq(memberships.userId, users.id))
    .where(
      and(
        eq(memberships.organizationId, organizationId),
        inArray(memberships.role, ['owner', 'admin'])
      )
    );

  return rows.map((r) => r.email).filter(Boolean);
}

/** How long the presigned PDF link in a webhook payload stays usable. */
const PDF_URL_TTL_SECONDS = 3600;

/** Entities whose PDF is generated by the application. */
const PDF_GENERATORS: Partial<
  Record<
    EntityKind,
    (id: string, organizationId: string, ip?: string) => Promise<{ fileId: string }>
  >
> = {
  quote: generateQuotePdf,
  invoice: generateInvoicePdf,
  contract: generateContractPdf,
};

/**
 * Presigned R2 link to the entity's generated PDF.
 *
 * This used to be `/api/v1/<entity>/<id>/pdf/download`, which n8n called with
 * its API key. That could never work: `n8n_primary` is a global endpoint
 * receiving events from every organization, while an API key belongs to exactly
 * one — so every PDF from any other organization answered 404, and tenant
 * isolation was right to refuse. Signing the object directly removes the need
 * for a credential entirely, works for all organizations, and the link expires
 * on its own.
 *
 * The document is rendered here if it does not exist yet. That matters: the PDF
 * is generated lazily, and measured on real events it landed up to a minute
 * *after* the transition emitted its event. Merely looking the file up would have
 * found nothing and every email would have shipped without its attachment.
 *
 * Returns null if generation fails, so the email goes out with a portal link
 * instead of an attachment rather than not going out at all.
 */
async function buildPdfUrl(
  organizationId: string,
  entityKind: EntityKind,
  entityId: string,
  entity: Record<string, any>
): Promise<string | null> {
  const generate = PDF_GENERATORS[entityKind];
  if (!generate) return null;

  // A signed contract must carry the signed rendering, not the draft one.
  const preferredFileId: string | null =
    entityKind === 'contract' && entity.status === 'signed'
      ? entity.signedPdfFileId ?? entity.pdfFileId ?? null
      : entity.pdfFileId ?? null;

  let fileId = preferredFileId;

  if (!fileId) {
    const generated = await generate(entityId, organizationId, undefined);
    fileId = generated.fileId;
  }

  if (!fileId) return null;

  const [file] = await db
    .select({
      r2Key: files.r2Key,
      filename: files.filename,
      organizationId: files.organizationId,
      status: files.status,
    })
    .from(files)
    .where(eq(files.id, fileId))
    .limit(1);

  // Tenant check even on a pointer read: `getPresignedGetUrl` refuses a key from
  // another organization, and a stale pointer must not reach it.
  if (!file || file.organizationId !== organizationId || file.status !== 'ready') {
    return null;
  }

  return getPresignedGetUrl(file.r2Key, organizationId, PDF_URL_TTL_SECONDS, file.filename);
}

export type BuildPayloadParams = {
  organizationId: string;
  entityKind: EntityKind;
  entityId: string;
  /** Entity row; `number`, `title` and `totalCents` are used when present. */
  entity: Record<string, any>;
  /** Mint a portal token and expose `portalUrl` (recipient-facing emails). */
  withPortalUrl?: boolean;
  /** Expose a `pdfUrl` the n8n workflow can download and attach. */
  withPdfUrl?: boolean;
  /** Extra fields merged last, e.g. `{ reason }` or `{ rating }`. */
  extra?: Record<string, unknown>;
};

/**
 * Assembles the event `data` object.
 *
 * @returns Payload shaped for the n8n email templates; enrichment that fails is
 *   simply omitted rather than thrown.
 */
export async function buildEventPayload(
  params: BuildPayloadParams
): Promise<Record<string, unknown>> {
  const { organizationId, entityKind, entityId, entity, extra } = params;

  const payload: Record<string, unknown> = {
    id: entityId,
    [`${entityKind}Id`]: entityId,
    number: entity.number ?? null,
    title: entity.title ?? null,
    status: entity.status ?? null,
  };

  const currency: string = entity.currency ?? 'XOF';

  if (entity.totalCents !== undefined && entity.totalCents !== null) {
    // Decimal string, like the API returns for the same column and like
    // `toJsonSafe` produces for the raw rows other call sites emit. `Number()`
    // here made the field's type depend on which code path built the event.
    payload.totalCents = String(entity.totalCents);
    payload.currency = currency;
    // Preformatted here on purpose: the email templates run inside n8n Code
    // nodes, which cannot import `lib/money.ts`. Sending the label rather than
    // asking them to divide keeps the XOF convention in exactly one place —
    // it had already drifted across four surfaces once.
    payload.totalLabel = formatMoney(entity.totalCents, currency);
  }

  // What a dunning email actually needs to state.
  if (entity.amountDueCents !== undefined && entity.amountDueCents !== null) {
    payload.amountDueCents = String(entity.amountDueCents);
    payload.amountDueLabel = formatMoney(entity.amountDueCents, currency);
  }

  try {
    const [org] = await db
      .select({
        name: organizations.name,
        brandColor: organizations.brandColor,
        logoFileId: organizations.logoFileId,
      })
      .from(organizations)
      .where(eq(organizations.id, organizationId))
      .limit(1);

    if (org) {
      payload.org = {
        name: org.name,
        brandColor: org.brandColor ?? '#2B6CE5',
        // The MJML templates have always read `{{org.logoUrl}}`, but the payload
        // never carried it, so no email ever showed a logo. Public and stable
        // rather than presigned: a mail client opening the message days later
        // must still resolve the image.
        logoUrl: org.logoFileId
          ? `${baseUrl()}/api/v1/organizations/${organizationId}/logo`
          : '',
      };
    }

    payload.teamEmails = await loadTeamEmails(organizationId);
    payload.ownerEmail = (payload.teamEmails as string[])[0] ?? null;

    let recipientEmail: string | null = null;

    // Deliverables hang off a project and carry no `client_id` of their own, so
    // the client has to be resolved one hop further. Without this, every
    // deliverable event went out with no `client`, the n8n template threw
    // "aucun destinataire résolu", and no portal link was ever minted either.
    let clientId: string | null = entity.clientId ?? null;

    if (!clientId && entity.projectId) {
      const [project] = await db
        .select({ clientId: projects.clientId })
        .from(projects)
        .where(and(eq(projects.id, entity.projectId), eq(projects.organizationId, organizationId)))
        .limit(1);

      clientId = project?.clientId ?? null;
    }

    if (clientId) {
      const [client] = await db
        .select({
          displayName: clients.displayName,
          email: clients.email,
        })
        .from(clients)
        .where(and(eq(clients.id, clientId), eq(clients.organizationId, organizationId)))
        .limit(1);

      if (client) {
        recipientEmail = client.email;
        payload.client = { name: client.displayName, email: client.email };
        payload.clientName = client.displayName;
      }
    }

    if (params.withPortalUrl && recipientEmail) {
      const token = await generatePublicToken({
        organizationId,
        resourceType: entityKind,
        resourceId: entityId,
        recipientEmail,
        actions: PORTAL_ACTIONS[entityKind],
      });

      payload.portalUrl = `${baseUrl()}/portal/${PORTAL_PATH[entityKind]}/${entityId}?token=${token.token}`;
    }

    if (params.withPdfUrl) {
      const pdfUrl = await buildPdfUrl(organizationId, entityKind, entityId, entity);
      if (pdfUrl) {
        payload.pdfUrl = pdfUrl;
      }
    }
  } catch (error) {
    // A webhook payload is never worth failing a business transition for.
    console.error('buildEventPayload: enrichment failed', error);
  }

  return { ...payload, ...(extra ?? {}) };
}
